import localfont from "next/font/local";

const myFont = localfont({
  src: [
    {
      path: "./fonts/anakotmai-medium.woff2",
    },
  ],
});

// import { Kanit } from "next/font/google";

import "./globals.css";
import { Suspense } from "react";
import Spinner from "@/components/Spinner";
import NavbarComponent from "../components/Navbar";
import Footer from "@/components/Footer";
import Container from "@/components/Container";
import { AuthProvider } from "./Provider";

// const kanit = Kanit({
//   subsets: ["thai"],
//   display: "swap",
//   weight: ["300", "500", "700", "600"],
// });
export const metadata = {
  title: "Charin Wongpantiang",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className} bg-slate-50`}>
        <Suspense fallback={<Spinner />}>
          <div className="flex flex-col justify-between w-full h-screen">
            <AuthProvider>
              <NavbarComponent />
              <Container>
                <main className="max-w-7xl  mx-auto w-full">{children}</main>
              </Container>
              <Footer />
            </AuthProvider>
          </div>
        </Suspense>
      </body>
    </html>
  );
}
